In [6]:
import pandas as pd
import utils

In [3]:
order_reviews_dataset = pd.read_csv("./dataset/olist_order_reviews_dataset.csv")
orders_dataset = pd.read_csv("./dataset/olist_orders_dataset.csv")

In [ ]:
orders_dataset['order_delivered_customer_date'] = pd.to_datetime(orders_dataset['order_delivered_customer_date'])
orders_dataset['order_estimated_delivery_date'] = pd.to_datetime(orders_dataset['order_estimated_delivery_date'])

In [8]:
merged = pd.merge(orders_dataset, order_reviews_dataset, on= 'order_id')

merged.drop(columns= ['review_comment_title', 'review_comment_message'], inplace= True)

In [9]:
utils.missing_value_report(merged)

                               missing_count  missing_pct
order_delivered_customer_date           2865         2.89
order_delivered_carrier_date            1756         1.77
order_approved_at                        156         0.16
order_id                                   0         0.00
order_purchase_timestamp                   0         0.00
order_status                               0         0.00
customer_id                                0         0.00
order_estimated_delivery_date              0         0.00
review_id                                  0         0.00
review_score                               0         0.00
review_creation_date                       0         0.00
review_answer_timestamp                    0         0.00

In [15]:
merged.dropna(inplace= True)

utils.missing_value_report(merged)

                               missing_count  missing_pct
order_id                                   0          0.0
customer_id                                0          0.0
order_status                               0          0.0
order_purchase_timestamp                   0          0.0
order_approved_at                          0          0.0
order_delivered_carrier_date               0          0.0
order_delivered_customer_date              0          0.0
order_estimated_delivery_date              0          0.0
review_id                                  0          0.0
review_score                               0          0.0
review_creation_date                       0          0.0
review_answer_timestamp                    0          0.0

In [18]:
merged.info()

<class 'pandas.DataFrame'>
Index: 96344 entries, 0 to 99223
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96344 non-null  str
 1   customer_id                    96344 non-null  str
 2   order_status                   96344 non-null  str
 3   order_purchase_timestamp       96344 non-null  str
 4   order_approved_at              96344 non-null  str
 5   order_delivered_carrier_date   96344 non-null  str
 6   order_delivered_customer_date  96344 non-null  datetime64[us]
 7   order_estimated_delivery_date  96344 non-null  str
 8   review_id                      96344 non-null  str
 9   review_score                   96344 non-null  int64
 10  review_creation_date           96344 non-null  str
 11  review_answer_timestamp        96344 non-null  str
dtypes: datetime64[us](1), int64(1), str(10)
memory usage: 9.6 MB

In [20]:
merged.info()

<class 'pandas.DataFrame'>
Index: 96344 entries, 0 to 99223
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96344 non-null  str
 1   customer_id                    96344 non-null  str
 2   order_status                   96344 non-null  str
 3   order_purchase_timestamp       96344 non-null  str
 4   order_approved_at              96344 non-null  str
 5   order_delivered_carrier_date   96344 non-null  str
 6   order_delivered_customer_date  96344 non-null  datetime64[us]
 7   order_estimated_delivery_date  96344 non-null  datetime64[us]
 8   review_id                      96344 non-null  str
 9   review_score                   96344 non-null  int64
 10  review_creation_date           96344 non-null  str
 11  review_answer_timestamp        96344 non-null  str
dtypes: datetime64[us](2), int64(1), str(9)
memory usage: 9.6 MB

In [26]:
merged['delay'] = (merged['order_delivered_customer_date'] - merged['order_estimated_delivery_date']).dt.days

merged['delay'].describe()

count    96344.000000
mean       -11.916497
std         10.113637
min       -147.000000
25%        -17.000000
50%        -12.000000
75%         -7.000000
max        188.000000
Name: delay, dtype: float64

In [ ]:
merged['is_late'] = order